version: '3'
services:
    bv_backend:
      build: ./
      # wait for sql up
      command: sh -c "sleep 40s ; uvicorn --factory app:create_app --host 0.0.0.0 --port 8000"
      ports:
        - "8000:8000"
      links:
        - "bv_sql"
      depends_on:
        - "bv_sql"
      hostname: "bv_backend"
      restart: always